version: '3.8'


# In the docker compose file, we define a number of services (containers) we want to run.
services:

  # We want to run MariaDB as a database server
  # We tried mysql but initializing data did not work
  mariadb:
    image: mariadb
    environment: # Configuration of the database server as specified in their README
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD?:}
      MYSQL_DATABASE: ${DATABASE_NAME?:}
      MYSQL_USER: ${DATABASE_USER?:}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD?:}
    ports: # We expose the database on the port specified in the .env file
      - ${DATABASE_PORT:-3306}:3306
    volumes:
      # We store the database files in ./data/db in our repository
      - ./database/db:/var/lib/mysql
        # We mount the SQL dump files in ./data/sql to automatically seed the database
      - "./database/sql:/docker-entrypoint-initdb.d"
    restart: always

  backend-express:
    image: webeng-tutorial/backend-express
    build:
      context: ./backend-express
    depends_on:
      - mariadb
    environment:
      - TYPEORM_HOST=mariadb
      - DATABASE_USER=${DATABASE_USER?:}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD?:}
      - DATABASE_NAME=${DATABASE_NAME?:}
      - DATABASE_PORT=3306
    ports:
      - ${BACKEND_EXPRESS_PORT?:}:80

  frontend-vanilla:
    image: webeng-tutorial/frontend-vanilla
    build:
      context: ./frontend-vanilla
    ports:
      - ${FRONTEND_VANILLA_PORT?:}:80
  